# Assignment 5

**Write a NumPy program to test whether none of the elements of a given array is zero**

In [1]:
import numpy as np

In [58]:
def chick_all_zeros(arr):
    import numpy as np
    if type(arr) == list:
        arr = np.array(arr)
        return "zeros" if np.all(arr==0) else "none zeros"
    
    elif type(arr) == np.ndarray:
        return "zeros" if np.all(arr==0) else "none zeros"
    
    else:
        "invalide type of data"
     

In [59]:
l = [1 , 2 , 3 , 0  , 5]
chick_all_zeros(l)

'none zeros'

In [60]:
a = np.array([0,0,0,0])

chick_all_zeros(a)

'zeros'

**Write a NumPy program to test whether any of the elements of a given array is non-zero**

In [61]:
def chick_any_zeros(arr):
    import numpy as np
    if type(arr) == list:
        arr = np.array(arr)
        return "zeros" if np.any(arr==0) else "none zeros"
    
    elif type(arr) == np.ndarray:
        return "zeros" if np.any(arr==0) else "none zeros"
    
    else:
        "invalide type of data"
     

In [62]:
l = [1 , 2 , 3 , 0  , 5]
chick_any_zeros(l)

'zeros'

**Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two 
given**

In [1]:
import numpy as np

In [7]:

class Compar:
    
    def __init__(self , arr1 , arr2 , tol):
        self.arr1 = arr1
        self.arr2 = arr2
        self.tol = tol
       
    def is_equal(self):
        if np.allclose(self.arr1 , self.arr2 , self.tol ) == True:
            return "is equal"
        else:
            return "not equal"
    
    def is_equal_tol(self):
        if np.allclose(self.arr1 , self.arr2 , self.tol) == True:
            return "is equal"
        else:
            return "not equal"
    
    

In [8]:
m = np.array([1,2,3,4,5,6])
n = np.array([1,2,3,4,5,6])
c = Compar(m , n , 1)
c.is_equal_tol()

'is equal'

In [9]:
m = np.array([1,2,3,4,90,6])
n = np.array([1,2,3,4,5,6])
c1 = Compar(m , n , 0)
c1.is_equal()

'not equal'

**Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives**

In [17]:
def creat_z_o_f():
    return np.zeros(10) , np.ones(10) , np.ones(10)*5

In [19]:
creat_z_o_f()

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]))

**Write a NumPy program to create an array of the integers from 30 to70**

In [23]:
def get_array(start , end):
    return np.arange(start , end + 1)

get_array(30 , 70)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

**Write a NumPy program to create a 3x3 identity matrix**

In [26]:
def creat_mat(shape):
    return np.identity(shape)

creat_mat(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Write a NumPy program to generate a random number between 0 and 1**

In [36]:
def random_num():
    return np.random.rand( 1)

random_num()

array([0.8966073])

**Write a NumPy program to generate an array of 15 random numbers from a standard normal 
distribution**

In [38]:
def genreat_nums(start , end):
    return np.random.randn(start , end)

genreat_nums(1,15)

array([[-0.01576233,  0.86751068,  1.32501786, -0.99990586,  0.86958617,
        -0.85467547, -1.84221678,  0.2970114 ,  0.32485045, -1.1200284 ,
        -0.41418842,  1.28174429, -0.76911003,  0.31541271,  1.39423954]])

**Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values 
except the first and last.**

In [41]:
def creat_vec(start , end):
    res = np.arange(start+1 , end)
    return res

creat_vec(15 , 55)

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

**Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10**

In [44]:
def creat_vec_l():
    res = np.linspace(0, 10 , 5)
    return res

creat_vec_l()

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

**Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal 
to 1, and inside 0.**

In [12]:
def creat_mat():
    mat = np.zeros((10 , 10))
    mat[0] = 1
    mat[-1] = 1
    mat[: , :1] = 1
    mat[: , -1:] = 1
    return mat

creat_mat()

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

**Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 
3, 4, 5.**

In [23]:
def matr():
    m = np.zeros((5 , 5))
    m[0 , :1] = 1
    m[1 , 1:2] = 2
    m[2 , 2:3] = 3
    m[3 , 3:4] = 4
    m[4 , 4:5] = 5
    
    return m

matr()

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])